language: php

php:
  - 7.2
  - 7.3

before_install:
  - SYMFONY_DEPENDENCIES=$(cat composer.json | jq '.require | to_entries[] | "\(.key):\(.value)"' | egrep -o '(symfony\/[^:]+)[^|]+\|' | egrep -o '(symfony\/[^:]+)'); for SYMFONY_DEPENDENCY in $SYMFONY_DEPENDENCIES; do composer require "${SYMFONY_DEPENDENCY}:${SYMFONY_VERSION}" --no-update; done

install: composer install --no-interaction

script: composer run-coverage

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=^3.4
    - php: 7.3
      env: SYMFONY_VERSION=^3.4

env:
  global:
    - CC_TEST_REPORTER_ID=9aad8a8b7a7e1f56a69449094ed32b6a145e5e30e7e2901690c4a46273338c44
    - SYMFONY_VERSION=^4.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: EYz5ZfaCOcNXCnIX5XRU3g2RpqK0K4p7vDdg4pozC442cN7mZX3ObbvyWKwtEVt0/5M3ZACC8Q8vd76lm4Gq1d5PM0G4cAxY/7wVAxAXKWcW8n48vnOixujf5LavoWEWkJKoYVMX0BI6vMMWj/EF+6ITMKt7WQTHUARZ0CdGbNEgqFrKKd13j5jQ+xZI2/Uzoq/JyF5ynX5tLfo5gC3CT37FxrCjHHzy9fkycH0G2lYBdO8Swdyb6NVO8h9bQx5JV1ZDzL3sxrzyMoi8nR2V/2RUQhkR83TyOGrokNboaq7bOjrgM3WocBQGp2XvV9VDvXONBqlcmI1rcKNfS7WmXZnhdaAlGIQ9kxwpzeh2jVJg9nCwKUXmjAn9SPJfzZUQ/Sp9qEr7bGXTrupHH4JTpLDpcu/sof+Elb0HwKU/8IKrq5cEyzlEG2TsZ7EOxCWQa3RbZ1eiVktoFWX3Q6LYC4MaidrHSGxKRiMuRP13MP9wp40a5MrDS+pCYyN2vSeiSWW48ls5EhXRK+INW4IQiG0Po/pfDKEluyfA+t5WbTjgLc5MnhlduxHJv+mWk49NsAnlfas1xpGK4UIvn/RaKdjUZ6rdnQZOxM8cLbGiobMBPCl9CHjNy4VZzXZiQYli3zVnqHhDq6ilSiLuZSHJuPnJYsbzw5Sqn5VB3nPbQNM=
