services:
  PhpArsenal\SalesforceMapperBundle\Request\ParamConverter\SalesforceParamConverter:
    arguments:
      - '@PhpArsenal\SalesforceMapperBundle\Mapper'
      - '%salesforce_mapper.param_converter%'
    tags:
      - { name: controller.argument_value_resolver, priority: 150 }
